"""ALTER TABLE columns

Revision ID: d00ad8a27d8d
Revises: 968985c4d13f
Create Date: 2018-02-08 15:25:30.048164

"""

# revision identifiers, used by Alembic.
revision = 'd00ad8a27d8d'
down_revision = '968985c4d13f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    op.create_table('queryperformance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table', sa.String(length=200), nullable=False),
    sa.Column('avgmicrosec', sa.Integer(), nullable=False),
    sa.Column('err_count', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('queryperformance')
    # ### end Alembic commands ###