"""ALTER TABLE column

Revision ID: 968985c4d13f
Revises: 378782121a08
Create Date: 2018-02-08 15:12:09.663232

"""

# revision identifiers, used by Alembic.
revision = '968985c4d13f'
down_revision = '378782121a08'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('queryperformance', 'avgmicrosec', sa.String(1000), existing_type=mysql.VARCHAR(1000)),
    op.alter_column('queryperformance', 'err_count', sa.String(1000), existing_type=mysql.VARCHAR(1000)),
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
