"""ALTER TABLE queryperformance

Revision ID: b58cebb7e00b
Revises: d00ad8a27d8d
Create Date: 2018-02-09 14:11:00.055701

"""

# revision identifiers, used by Alembic.
revision = 'b58cebb7e00b'
down_revision = 'd00ad8a27d8d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('queryperformance', 'avgmicrosec', sa.Integer(), existing_type=mysql.Integer()),
    op.alter_column('queryperformance', 'err_count', sa.Integer(), existing_type=mysql.Integer()),
    op.add_column('queryperformance', sa.Column('table', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queryperformance', 'table')
    # ### end Alembic commands ###
