"""ADD TABLES [QueryThroughput, QueryPerformance, Connections, InnodbBufferPool]

Revision ID: 378782121a08
Revises: 
Create Date: 2018-02-03 17:12:24.255419

"""

# revision identifiers, used by Alembic.
revision = '378782121a08'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('max_connections', sa.Integer(), nullable=False),
    sa.Column('threads_connected', sa.Integer(), nullable=False),
    sa.Column('threads_running', sa.Integer(), nullable=False),
    sa.Column('connection_errors_internal', sa.Integer(), nullable=False),
    sa.Column('aborted_connects', sa.Integer(), nullable=False),
    sa.Column('connection_errors_max_connections', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('innodbbufferpool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('innodb_buffer_pool_pages_total', sa.Integer(), nullable=False),
    sa.Column('innodb_buffer_pool_rate', sa.Integer(), nullable=False),
    sa.Column('innodb_buffer_pool_read_requests', sa.Integer(), nullable=False),
    sa.Column('innodb_buffer_pool_reads', sa.Integer(), nullable=False),
    sa.Column('innodb_page_size', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('queryperformance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('avgmicrosec', sa.String(length=50), nullable=False),
    sa.Column('err_count', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('querythrougput',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('questions', sa.Integer(), nullable=False),
    sa.Column('com_select', sa.Integer(), nullable=False),
    sa.Column('writes', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('querythrougput')
    op.drop_table('queryperformance')
    op.drop_table('innodbbufferpool')
    op.drop_table('connections')
    ### end Alembic commands ###
