AGENT_DB:
    host: '127.0.0.1'
    port: 3306
    user: 'root'
    password: 'sk927312*'
    db: 'dbmonitor'
HOSTNAME: '127.0.0.1'
SERVER_DB:
    host: '127.0.0.1'
    port: 3306
    user: 'root'
    password: 'sk927312*'
    db: 'dbmonitor'
